### ISSUE TITLE
Adding Annotations

### ISSUE THREAD

**Issue by giovanniorigins** [alakra/cordova-mbxmapkit#11]
Hi and thanks for maintaining the plugin!

How do you add annotations to the map? I'm able to create an annotation, but i don't see it anywhere on the map.

**Comment by giovanniorigins** [comment]
Update: I am able to get annotations to appear now.
Looking at the code, I'm guessing the annotation type is the image that is used. Do you have any examples of linking to an image?

**Comment by alakra** [comment]
I apologize for not answering this sooner, but I am not supporting this project any more.  MapBox has some great libraries now that should fill the gap for you.  

Good luck!
